# Generated by Django 3.0.2 on 2020-02-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('explicit_url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('named_url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.MenuItem')),
            ],
        ),
    ]
